// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dataom.app.domain;

import com.dataom.app.domain.Segment;
import java.math.BigInteger;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Persistent;

privileged aspect Segment_Roo_Mongo_Entity {
    
    declare @type: Segment: @Persistent;
    
    @Id
    private BigInteger Segment.id;
    
    public BigInteger Segment.getId() {
        return this.id;
    }
    
    public void Segment.setId(BigInteger id) {
        this.id = id;
    }
    
}
