// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dataom.app.dao;

import com.dataom.app.dao.SegmentDao;
import com.dataom.app.domain.Segment;
import java.math.BigInteger;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.stereotype.Repository;

privileged aspect SegmentDao_Roo_Mongo_Repository {
    
    declare parents: SegmentDao extends PagingAndSortingRepository<Segment, BigInteger>;
    
    declare @type: SegmentDao: @Repository;
    
}
