// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dataom.app.domain;

import com.dataom.app.domain.Attr;

privileged aspect Attr_Roo_JavaBean {
    
    public String Attr.getName() {
        return this.name;
    }
    
    public void Attr.setName(String name) {
        this.name = name;
    }
    
    public String Attr.getDescription() {
        return this.description;
    }
    
    public void Attr.setDescription(String description) {
        this.description = description;
    }
    
    public String Attr.getDn() {
        return this.dn;
    }
    
    public void Attr.setDn(String dn) {
        this.dn = dn;
    }
    
    public String Attr.getParams() {
        return this.params;
    }
    
    public void Attr.setParams(String params) {
        this.params = params;
    }
    
    public String Attr.getExpr() {
        return this.expr;
    }
    
    public void Attr.setExpr(String expr) {
        this.expr = expr;
    }
    
    public Boolean Attr.getDisabled() {
        return this.disabled;
    }
    
    public void Attr.setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }
    
    public Long Attr.getPopulation60d() {
        return this.population60d;
    }
    
    public void Attr.setPopulation60d(Long population60d) {
        this.population60d = population60d;
    }
    
    public Long Attr.getPopulation30d() {
        return this.population30d;
    }
    
    public void Attr.setPopulation30d(Long population30d) {
        this.population30d = population30d;
    }
    
    public Long Attr.getPopulationDaily() {
        return this.populationDaily;
    }
    
    public void Attr.setPopulationDaily(Long populationDaily) {
        this.populationDaily = populationDaily;
    }
    
}
