// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dataom.app.domain;

import com.dataom.app.domain.Attr;
import java.math.BigInteger;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Persistent;

privileged aspect Attr_Roo_Mongo_Entity {
    
    declare @type: Attr: @Persistent;
    
    @Id
    private BigInteger Attr.id;
    
    public BigInteger Attr.getId() {
        return this.id;
    }
    
    public void Attr.setId(BigInteger id) {
        this.id = id;
    }
    
}
